version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    assignees:
      - "username"
    reviewers:
      - "username"
    commit-message:
      prefix: "npm"
      include: "scope"
    versioning-strategy: auto
    ignore:
      - dependency-name: "@riavzon/botdetector"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
